name: Dependabot Jira

on:
  pull_request_target:
    branches:
      - 4.6.x
      - main

    types:
      - opened
      - reopened

jobs:
  summary:
    if: github.actor == 'dependabot[bot]' && !contains(github.event.pull_request.labels.*.name, 'github_actions')
    runs-on: ubuntu-latest

    outputs:
      summary: ${{ steps.summary.outputs.summary }}

    steps:
      - id: summary
        run: echo summary=$(echo ${{ github.event.pull_request.title }} | grep -oP '(?<=Bump )(.*)(?=from)|(?<=to )(.*)' | tr -d '\n') >> $GITHUB_OUTPUT

#  jira:
#    needs: summary
#    uses: infinispan/infinispan/.github/workflows/jira_upsert.yml@main
#    secrets:
#      token: ${{ secrets.JIRA_API_TOKEN }}
#    with:
#      infinispanBranch: main
#      project: IPROTO
#      summary: ${{ needs.summary.outputs.summary }}
#      type: Component Upgrade
#      pullRequest: ${{ github.event.pull_request.html_url }}
#
#  comment:
#    needs: jira
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write
#    steps:
#      - name: Add comment to PR
#        uses: actions/github-script@v7
#        with:
#          script: |
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '${{ needs.jira.outputs.url }}'
#            })
