name: Pull Request Merged

on:
  pull_request:
    branches:
      - 4.6.x
      - main
    types:
      - closed

jobs:
  updateJira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          repository: infinispan/infinispan

      - name: Extract Jira Key
        run: echo ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'IPROTO-(?P<id>[0-9]+)') >> $GITHUB_ENV

      - name: Add Fix Version
        if: ${{ env.ISSUE_KEY != '' }}
        run: ./bin/jira/add_fix_version.sh
        env:
          ISSUE_KEY: ${{ env.ISSUE_KEY }}
          TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          VERSION: ${{ github.event.pull_request.milestone.title }}

      - name: Transition Issue to Resolved
        if: ${{ env.ISSUE_KEY != '' }} && !contains(github.event.pull_request.labels.*.name, '4.6.x')
        run: ./bin/jira/transition.sh
        env:
          ISSUE_KEY: ${{ env.ISSUE_KEY }}
          TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TRANSITION: Resolved
