name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jdk11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: JDK 11 Tests
        run: mvn -B verify -Dmaven.test.failure.ignore=true -Dansi.strip=true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: "**/target/*-reports*/**/TEST-*.xml"
          reporter: java-junit        # Format of test results
